// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: company.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createCompany = `-- name: CreateCompany :one
INSERT INTO companies (
  name,
  registration_number,
  address_street,
  address_city,
  address_state,
  address_postal_code,
  address_country,
  primary_phone,
  secondary_phone,
  email,
  website,
  callback_url,
  return_url
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
RETURNING id, name, registration_number, address_street, address_city, address_state, address_postal_code, address_country, primary_phone, secondary_phone, email, status, website, callback_url, return_url, created_at, updated_at
`

type CreateCompanyParams struct {
	Name               string
	RegistrationNumber string
	AddressStreet      sql.NullString
	AddressCity        sql.NullString
	AddressState       sql.NullString
	AddressPostalCode  sql.NullString
	AddressCountry     sql.NullString
	PrimaryPhone       sql.NullString
	SecondaryPhone     sql.NullString
	Email              sql.NullString
	Website            sql.NullString
	CallbackUrl        sql.NullString
	ReturnUrl          sql.NullString
}

type CreateCompanyRow struct {
	ID                 uuid.UUID
	Name               string
	RegistrationNumber string
	AddressStreet      sql.NullString
	AddressCity        sql.NullString
	AddressState       sql.NullString
	AddressPostalCode  sql.NullString
	AddressCountry     sql.NullString
	PrimaryPhone       sql.NullString
	SecondaryPhone     sql.NullString
	Email              sql.NullString
	Status             string
	Website            sql.NullString
	CallbackUrl        sql.NullString
	ReturnUrl          sql.NullString
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

func (q *Queries) CreateCompany(ctx context.Context, arg CreateCompanyParams) (CreateCompanyRow, error) {
	row := q.db.QueryRow(ctx, createCompany,
		arg.Name,
		arg.RegistrationNumber,
		arg.AddressStreet,
		arg.AddressCity,
		arg.AddressState,
		arg.AddressPostalCode,
		arg.AddressCountry,
		arg.PrimaryPhone,
		arg.SecondaryPhone,
		arg.Email,
		arg.Website,
		arg.CallbackUrl,
		arg.ReturnUrl,
	)
	var i CreateCompanyRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RegistrationNumber,
		&i.AddressStreet,
		&i.AddressCity,
		&i.AddressState,
		&i.AddressPostalCode,
		&i.AddressCountry,
		&i.PrimaryPhone,
		&i.SecondaryPhone,
		&i.Email,
		&i.Status,
		&i.Website,
		&i.CallbackUrl,
		&i.ReturnUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCompanyToken = `-- name: CreateCompanyToken :one
INSERT INTO company_tokens (token_id, company_id) 
VALUES ($1, $2) 
RETURNING id, token_id, company_id, status, created_at, updated_at, deleted_at
`

type CreateCompanyTokenParams struct {
	TokenID   uuid.UUID
	CompanyID uuid.UUID
}

func (q *Queries) CreateCompanyToken(ctx context.Context, arg CreateCompanyTokenParams) (CompanyToken, error) {
	row := q.db.QueryRow(ctx, createCompanyToken, arg.TokenID, arg.CompanyID)
	var i CompanyToken
	err := row.Scan(
		&i.ID,
		&i.TokenID,
		&i.CompanyID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getActiveCompanyTokenByID = `-- name: GetActiveCompanyTokenByID :one
SELECT id, token_id, company_id, status, created_at, updated_at, deleted_at 
FROM company_tokens
WHERE company_id = $1 AND status = 'ACTIVE' AND deleted_at IS NULL
`

func (q *Queries) GetActiveCompanyTokenByID(ctx context.Context, companyID uuid.UUID) (CompanyToken, error) {
	row := q.db.QueryRow(ctx, getActiveCompanyTokenByID, companyID)
	var i CompanyToken
	err := row.Scan(
		&i.ID,
		&i.TokenID,
		&i.CompanyID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCompanyByID = `-- name: GetCompanyByID :one
SELECT id, name, registration_number, address_street, address_city, address_state, address_postal_code, address_country, primary_phone, secondary_phone, email, status, website, callback_url, return_url, created_at, updated_at
FROM companies
WHERE id = $1 AND deleted_at IS NULL
`

type GetCompanyByIDRow struct {
	ID                 uuid.UUID
	Name               string
	RegistrationNumber string
	AddressStreet      sql.NullString
	AddressCity        sql.NullString
	AddressState       sql.NullString
	AddressPostalCode  sql.NullString
	AddressCountry     sql.NullString
	PrimaryPhone       sql.NullString
	SecondaryPhone     sql.NullString
	Email              sql.NullString
	Status             string
	Website            sql.NullString
	CallbackUrl        sql.NullString
	ReturnUrl          sql.NullString
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

func (q *Queries) GetCompanyByID(ctx context.Context, id uuid.UUID) (GetCompanyByIDRow, error) {
	row := q.db.QueryRow(ctx, getCompanyByID, id)
	var i GetCompanyByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RegistrationNumber,
		&i.AddressStreet,
		&i.AddressCity,
		&i.AddressState,
		&i.AddressPostalCode,
		&i.AddressCountry,
		&i.PrimaryPhone,
		&i.SecondaryPhone,
		&i.Email,
		&i.Status,
		&i.Website,
		&i.CallbackUrl,
		&i.ReturnUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const inActiveCompanyToken = `-- name: InActiveCompanyToken :exec
UPDATE company_tokens ct 
SET status = 'INACTIVE'
WHERE ct.company_id = $1 
AND ct.deleted_at IS NULL 
AND ct.status = 'ACTIVE'
`

func (q *Queries) InActiveCompanyToken(ctx context.Context, companyID uuid.UUID) error {
	_, err := q.db.Exec(ctx, inActiveCompanyToken, companyID)
	return err
}
