// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: customer.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers (
  company_id,
  full_name,
  phone_number,
  email
) VALUES (
  $1, $2, $3, $4
) ON CONFLICT (company_id, phone_number) WHERE deleted_at IS NULL
DO UPDATE SET email = excluded.email, full_name = excluded.full_name
RETURNING id, company_id, full_name, phone_number, email, status, created_at, updated_at, deleted_at
`

type CreateCustomerParams struct {
	CompanyID   uuid.UUID
	FullName    sql.NullString
	PhoneNumber string
	Email       sql.NullString
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, createCustomer,
		arg.CompanyID,
		arg.FullName,
		arg.PhoneNumber,
		arg.Email,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.FullName,
		&i.PhoneNumber,
		&i.Email,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
