// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgtype"
	"github.com/shopspring/decimal"
)

type Company struct {
	ID                 uuid.UUID
	Name               string
	RegistrationNumber string
	AddressStreet      sql.NullString
	AddressCity        sql.NullString
	AddressState       sql.NullString
	AddressPostalCode  sql.NullString
	AddressCountry     sql.NullString
	PrimaryPhone       sql.NullString
	SecondaryPhone     sql.NullString
	Status             string
	Email              sql.NullString
	Website            sql.NullString
	CallbackUrl        sql.NullString
	ReturnUrl          sql.NullString
	CreatedAt          time.Time
	UpdatedAt          time.Time
	DeletedAt          sql.NullTime
}

type CompanyToken struct {
	ID        uuid.UUID
	TokenID   uuid.UUID
	CompanyID uuid.UUID
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}

type Customer struct {
	ID          uuid.UUID
	CompanyID   uuid.UUID
	FullName    sql.NullString
	PhoneNumber string
	Email       sql.NullString
	Status      string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   sql.NullTime
}

type PaymentIntent struct {
	ID          uuid.UUID
	CompanyID   uuid.UUID
	CustomerID  uuid.UUID
	PaymentType string
	Amount      decimal.Decimal
	Currency    string
	CallbackUrl string
	ReturnUrl   string
	Description sql.NullString
	Extra       pgtype.JSON
	Status      string
	BillRefNo   sql.NullString
	ExpireAt    sql.NullTime
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   sql.NullTime
}

type User struct {
	ID                uuid.UUID
	CompanyID         uuid.UUID
	Username          sql.NullString
	Email             string
	Phone             string
	Password          string
	FirstName         sql.NullString
	LastName          sql.NullString
	Role              sql.NullString
	Status            string
	TimezoneID        sql.NullString
	Bio               sql.NullString
	ProfilePictureUrl sql.NullString
	CreatedAt         time.Time
	UpdatedAt         time.Time
	DeletedAt         sql.NullTime
}

type UserToken struct {
	ID        uuid.UUID
	TokenID   uuid.UUID
	UserID    uuid.UUID
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}
