// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payment_intent_worker.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const updatePaymentIntentStatus = `-- name: UpdatePaymentIntentStatus :one
UPDATE payment_intents
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, status, updated_at
`

type UpdatePaymentIntentStatusParams struct {
	ID     uuid.UUID
	Status string
}

type UpdatePaymentIntentStatusRow struct {
	ID        uuid.UUID
	Status    string
	UpdatedAt time.Time
}

func (q *Queries) UpdatePaymentIntentStatus(ctx context.Context, arg UpdatePaymentIntentStatusParams) (UpdatePaymentIntentStatusRow, error) {
	row := q.db.QueryRow(ctx, updatePaymentIntentStatus, arg.ID, arg.Status)
	var i UpdatePaymentIntentStatusRow
	err := row.Scan(&i.ID, &i.Status, &i.UpdatedAt)
	return i, err
}
