// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payment_intent.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgtype"
	"github.com/shopspring/decimal"
)

const createPaymentIntent = `-- name: CreatePaymentIntent :one
INSERT INTO payment_intents (
    company_id,
    customer_id,
    payment_type,
    amount,
    currency,
    callback_url,
    return_url,
    description,
    extra,
    status,
    bill_ref_no
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING id, company_id, customer_id, payment_type, amount, currency, callback_url, return_url, description, extra, status, bill_ref_no, expire_at, created_at, updated_at, deleted_at
`

type CreatePaymentIntentParams struct {
	CompanyID   uuid.UUID
	CustomerID  uuid.UUID
	PaymentType string
	Amount      decimal.Decimal
	Currency    string
	CallbackUrl string
	ReturnUrl   string
	Description sql.NullString
	Extra       pgtype.JSON
	Status      string
	BillRefNo   sql.NullString
}

func (q *Queries) CreatePaymentIntent(ctx context.Context, arg CreatePaymentIntentParams) (PaymentIntent, error) {
	row := q.db.QueryRow(ctx, createPaymentIntent,
		arg.CompanyID,
		arg.CustomerID,
		arg.PaymentType,
		arg.Amount,
		arg.Currency,
		arg.CallbackUrl,
		arg.ReturnUrl,
		arg.Description,
		arg.Extra,
		arg.Status,
		arg.BillRefNo,
	)
	var i PaymentIntent
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CustomerID,
		&i.PaymentType,
		&i.Amount,
		&i.Currency,
		&i.CallbackUrl,
		&i.ReturnUrl,
		&i.Description,
		&i.Extra,
		&i.Status,
		&i.BillRefNo,
		&i.ExpireAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPaymentIntentByID = `-- name: GetPaymentIntentByID :one
SELECT
    pi.id,
    pi.payment_type,
    pi.amount,
    pi.status,
    pi.currency,
    pi.callback_url,
    pi.return_url,
    pi.description,
    pi.extra,
    pi.bill_ref_no,
    pi.expire_at,
    pi.created_at,
    pi.updated_at,
    json_build_object (
        'id',cu.id,
        'company_id',cu.company_id,
        'full_name',cu.full_name,
        'phone_number',cu.phone_number,
        'email',cu.email,
        'created_at',cu.created_at,
        'updated_at',cu.updated_at
    ) AS customer,
    json_build_object (
        'id',c.id,
        'name',c.name,
        'registration_number',c.registration_number,
        'address_street',c.address_street,
        'address_city',c.address_city,
        'address_state',c.address_state,
        'address_postal_code',c.address_postal_code,
        'address_country',c.address_country,
        'primary_phone',c.primary_phone,
        'secondary_phone',c.secondary_phone,
        'status',c.status,
        'email',c.email,
        'website',c.website,
        'callback_url',c.callback_url,
        'return_url',c.return_url,
        'created_at',c.created_at,
        'updated_at',c.updated_at
    ) AS company
FROM 
    payment_intents pi 
JOIN 
    customers cu ON pi.customer_id = cu.id 
JOIN 
    companies c ON pi.company_id = c.id
WHERE 
    pi.id = $1 AND pi.deleted_at IS NULL AND c.deleted_at IS NULL AND cu.deleted_at IS NULL
`

type GetPaymentIntentByIDRow struct {
	ID          uuid.UUID
	PaymentType string
	Amount      decimal.Decimal
	Status      string
	Currency    string
	CallbackUrl string
	ReturnUrl   string
	Description sql.NullString
	Extra       pgtype.JSON
	BillRefNo   sql.NullString
	ExpireAt    sql.NullTime
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Customer    pgtype.JSON
	Company     pgtype.JSON
}

func (q *Queries) GetPaymentIntentByID(ctx context.Context, id uuid.UUID) (GetPaymentIntentByIDRow, error) {
	row := q.db.QueryRow(ctx, getPaymentIntentByID, id)
	var i GetPaymentIntentByIDRow
	err := row.Scan(
		&i.ID,
		&i.PaymentType,
		&i.Amount,
		&i.Status,
		&i.Currency,
		&i.CallbackUrl,
		&i.ReturnUrl,
		&i.Description,
		&i.Extra,
		&i.BillRefNo,
		&i.ExpireAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Customer,
		&i.Company,
	)
	return i, err
}
