// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  company_id,
  first_name,
  email,
  phone,
  password
)
VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, company_id, username, email, phone, password, first_name, last_name, role, status, timezone_id, bio, profile_picture_url, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	CompanyID uuid.UUID
	FirstName sql.NullString
	Email     string
	Phone     string
	Password  string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.CompanyID,
		arg.FirstName,
		arg.Email,
		arg.Phone,
		arg.Password,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Username,
		&i.Email,
		&i.Phone,
		&i.Password,
		&i.FirstName,
		&i.LastName,
		&i.Role,
		&i.Status,
		&i.TimezoneID,
		&i.Bio,
		&i.ProfilePictureUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createUserToken = `-- name: CreateUserToken :one
INSERT INTO user_tokens (
  token_id,
  user_id
)
VALUES (
  $1, $2
)
RETURNING id, token_id, user_id, status, created_at, updated_at, deleted_at
`

type CreateUserTokenParams struct {
	TokenID uuid.UUID
	UserID  uuid.UUID
}

func (q *Queries) CreateUserToken(ctx context.Context, arg CreateUserTokenParams) (UserToken, error) {
	row := q.db.QueryRow(ctx, createUserToken, arg.TokenID, arg.UserID)
	var i UserToken
	err := row.Scan(
		&i.ID,
		&i.TokenID,
		&i.UserID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getActiveUserTokenByUserID = `-- name: GetActiveUserTokenByUserID :one
SELECT id, token_id, user_id, status, created_at, updated_at, deleted_at 
FROM user_tokens
WHERE user_id = $1 AND status = 'ACTIVE' AND deleted_at IS NULL
`

func (q *Queries) GetActiveUserTokenByUserID(ctx context.Context, userID uuid.UUID) (UserToken, error) {
	row := q.db.QueryRow(ctx, getActiveUserTokenByUserID, userID)
	var i UserToken
	err := row.Scan(
		&i.ID,
		&i.TokenID,
		&i.UserID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, company_id, username, email, phone, password, first_name, last_name, role, status, timezone_id, bio, profile_picture_url, created_at, updated_at, deleted_at
FROM users 
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Username,
		&i.Email,
		&i.Phone,
		&i.Password,
		&i.FirstName,
		&i.LastName,
		&i.Role,
		&i.Status,
		&i.TimezoneID,
		&i.Bio,
		&i.ProfilePictureUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByPhoneOrEmail = `-- name: GetUserByPhoneOrEmail :one
SELECT id, company_id, username, email, phone, password, first_name, last_name, role, status, timezone_id, bio, profile_picture_url, created_at, updated_at, deleted_at
FROM users 
WHERE (email = $1 OR phone = $1) AND deleted_at IS NULL
`

func (q *Queries) GetUserByPhoneOrEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPhoneOrEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Username,
		&i.Email,
		&i.Phone,
		&i.Password,
		&i.FirstName,
		&i.LastName,
		&i.Role,
		&i.Status,
		&i.TimezoneID,
		&i.Bio,
		&i.ProfilePictureUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const phoneOrEmailExists = `-- name: PhoneOrEmailExists :one
SELECT EXISTS (
  SELECT 1 
  FROM users 
  WHERE (email = $1 OR phone = $1) AND deleted_at IS NULL
) AS email_or_phone_exists
`

func (q *Queries) PhoneOrEmailExists(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, phoneOrEmailExists, email)
	var email_or_phone_exists bool
	err := row.Scan(&email_or_phone_exists)
	return email_or_phone_exists, err
}

const resetActiveToken = `-- name: ResetActiveToken :exec
UPDATE user_tokens
SET status = 'INACTIVE', updated_at = NOW()
WHERE user_id = $1 AND status = 'ACTIVE' AND deleted_at IS NULL
`

func (q *Queries) ResetActiveToken(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, resetActiveToken, userID)
	return err
}

const usernameExists = `-- name: UsernameExists :one
SELECT EXISTS (
  SELECT 1 
  FROM users 
  WHERE username = $1 AND deleted_at IS NULL
) AS username_exists
`

func (q *Queries) UsernameExists(ctx context.Context, username sql.NullString) (bool, error) {
	row := q.db.QueryRow(ctx, usernameExists, username)
	var username_exists bool
	err := row.Scan(&username_exists)
	return username_exists, err
}
